/**
 * Verifies that all mdi-react icon imports used in the codebase are
 * resolvable in the currently-installed version of mdi-react.
 *
 * This test was added during the mdi-react 6.7.0 → 9.4.0 upgrade to
 * provide systematic evidence that every icon import across the entire UI
 * codebase resolves correctly. Between these versions the underlying MDI
 * icon set went from v4.9.95 to v7.4.47 and several icons were renamed or
 * removed; the six that were actually used in this codebase were replaced in
 * the accompanying commits.
 *
 * Note: mdi-react v9 continues to use the same per-file import pattern
 * (`import FooIcon from 'mdi-react/FooIcon'`) as previous versions — the
 * import *syntax* did not change, only individual icon availability.
 */

// All unique mdi-react icon modules imported anywhere in src/
// Generated by: grep -r "from 'mdi-react/" src --include="*.js" --include="*.jsx"
//               | grep -o "'mdi-react/[^']*'" | sort -u
const USED_ICON_MODULES = [
  'mdi-react/AccountCircleIcon',
  'mdi-react/AccountHeartOutlineIcon',
  'mdi-react/AccountIcon',
  'mdi-react/AccountKeyIcon',
  'mdi-react/AccountMultipleIcon',
  'mdi-react/AccountSettingsIcon',
  'mdi-react/AccountStarIcon',
  'mdi-react/AlertCircleIcon',
  'mdi-react/AlertCircleOutlineIcon',
  'mdi-react/AlertIcon',
  'mdi-react/ArchiveIcon',
  'mdi-react/ArrowDownBoldCircleOutlineIcon',
  'mdi-react/ArrowExpandVerticalIcon',
  'mdi-react/ArrowLeftIcon',
  'mdi-react/ArrowRightIcon',
  'mdi-react/AutorenewIcon',
  'mdi-react/BackupRestoreIcon',
  'mdi-react/BellIcon',
  'mdi-react/BookOpenOutlineIcon',
  'mdi-react/BookOpenPageVariantIcon',
  'mdi-react/BookOpenVariantIcon',
  'mdi-react/CalendarClockIcon',
  'mdi-react/CalendarIcon',
  'mdi-react/CancelIcon',
  'mdi-react/ChartBarIcon',
  'mdi-react/CheckCircleIcon',
  'mdi-react/CheckIcon',
  'mdi-react/ChevronDownIcon',
  'mdi-react/ChevronLeftIcon',
  'mdi-react/ChevronRightIcon',
  'mdi-react/ChevronUpIcon',
  'mdi-react/ClearIcon',
  'mdi-react/ClockOutlineIcon',
  'mdi-react/CloseIcon',
  'mdi-react/ConsoleIcon',
  'mdi-react/ConsoleLineIcon',
  'mdi-react/ContentCopyIcon',
  'mdi-react/ContentSaveIcon',
  'mdi-react/CreationIcon',
  'mdi-react/DeleteIcon',
  'mdi-react/DotsVerticalIcon',
  'mdi-react/DownloadIcon',
  'mdi-react/ExpandMoreIcon',
  'mdi-react/FeatureSearchIcon',
  'mdi-react/FileCodeIcon',
  'mdi-react/FileDocumentIcon',
  'mdi-react/FileExcelIcon',
  'mdi-react/FileIcon',
  'mdi-react/FileImageIcon',
  'mdi-react/FileMusicIcon',
  'mdi-react/FilePdfBoxIcon',
  'mdi-react/FilePowerpointIcon',
  'mdi-react/FileTreeIcon',
  'mdi-react/FileVideoIcon',
  'mdi-react/FileWordIcon',
  'mdi-react/FilterIcon',
  'mdi-react/FlashIcon',
  'mdi-react/FormatListChecksIcon',
  'mdi-react/GestureTapIcon',
  'mdi-react/GithubIcon',
  'mdi-react/GroupIcon',
  'mdi-react/HammerIcon',
  'mdi-react/HelpIcon',
  'mdi-react/HexagonIcon',
  'mdi-react/HexagonMultipleIcon',
  'mdi-react/HexagonSlice4Icon',
  'mdi-react/HomeLockIcon',
  'mdi-react/HomeLockOpenIcon',
  'mdi-react/HourglassIcon',
  'mdi-react/InformationIcon',
  'mdi-react/InformationOutlineIcon',
  'mdi-react/InformationVariantIcon',
  'mdi-react/KeyboardOutlineIcon',
  'mdi-react/KeyIcon',
  'mdi-react/LibraryIcon',
  'mdi-react/LightbulbOnIcon',
  'mdi-react/LightbulbOnOutlineIcon',
  'mdi-react/LinkIcon',
  'mdi-react/LockResetIcon',
  'mdi-react/LoginVariantIcon',
  'mdi-react/LogoutVariantIcon',
  'mdi-react/MagnifyIcon',
  'mdi-react/MenuIcon',
  'mdi-react/MessageAlertIcon',
  'mdi-react/NavigateNextIcon',
  'mdi-react/NumericIcon',
  'mdi-react/OneTwoThreeIcon',
  'mdi-react/OpenInNewIcon',
  'mdi-react/PencilIcon',
  'mdi-react/PlayIcon',
  'mdi-react/PlaylistRemoveIcon',
  'mdi-react/PlusCircleIcon',
  'mdi-react/PlusIcon',
  'mdi-react/PowerIcon',
  'mdi-react/ProgressClockIcon',
  'mdi-react/PulseIcon',
  'mdi-react/RestartIcon',
  'mdi-react/RotateLeftIcon',
  'mdi-react/RunIcon',
  'mdi-react/ScaleBalanceIcon',
  'mdi-react/ServerNetworkIcon',
  'mdi-react/ShovelIcon',
  'mdi-react/StopIcon',
  'mdi-react/TimerSandIcon',
  'mdi-react/WebhookIcon',
];

describe('mdi-react icon imports', () => {
  it('all icon modules used in the codebase are resolvable in mdi-react 9.4.0', () => {
    const missing = [];

    for (const modulePath of USED_ICON_MODULES) {
      try {
        // eslint-disable-next-line import/no-dynamic-require
        const mod = require(modulePath);
        // The module should export a React component (function or object)
        if (!mod || (typeof mod !== 'function' && typeof mod !== 'object')) {
          missing.push(`${modulePath}: exports unexpected value`);
        }
      } catch (e) {
        missing.push(`${modulePath}: ${e.message}`);
      }
    }

    if (missing.length > 0) {
      throw new Error(
        `The following mdi-react icon modules could not be resolved:\n${missing.join('\n')}\n\n` +
          'These icons were likely removed in a newer version of the MDI icon set. ' +
          'Update the imports to use replacement icon names.'
      );
    }
  });
});
